# -*- coding: utf-8 -*-
"""yolo fine tune

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JE3o3_v6nv08T9184JMWI511FpDt_VTO
"""

from google.colab import files
uploaded = files.upload()  # Upload your Violence-1.zip file here



!unzip Violence.v1i.yolov8.zip -d .

!pip install ultralytics

!yolo task=detect mode=train model=yolov8n.pt data=data.yaml epochs=50 imgsz=640

from google.colab import files
files.download('runs/detect/train2/weights/best.pt')

from ultralytics import YOLO
import cv2
import os

# Load fine-tuned model
model = YOLO("best.pt")  # path to your fine-tuned model

# Input video path
input_path = "V_970.mp4"
output_path = "output_annotated_video.avi"

# Open video
cap = cv2.VideoCapture(input_path)
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = cap.get(cv2.CAP_PROP_FPS)

# Create video writer
fourcc = cv2.VideoWriter_fourcc(*"XVID")
out = cv2.VideoWriter(output_path, fourcc, fps, (width, height))

# Inference frame-by-frame
while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Run YOLOv8 inference
    results = model.predict(frame, imgsz=640, conf=0.3, verbose=False)[0]

    # Annotate frame
    annotated_frame = results.plot()

    # Write to output
    out.write(annotated_frame)

cap.release()
out.release()

print(f"✅ Done! Output saved at: {output_path}")